# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Professional'),
        ),
    ]
