# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170910_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='professional',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
